---
- name: cloud nodes setup
  hosts: CLOUD
  roles:
  - { role: cloud}

- name: pulp deployment
  hosts: pulp
  roles:
  - { role: pulp }

- name: build master deployment
  hosts: build_master
  roles:
  - { role: build_master}
